# -*- coding: UTF-8 -*-
import sys
import os

print "Generating emojitex-characters.sty ..."
os.chdir(os.path.dirname(os.path.abspath(sys.argv[0])))
f = open('../coloremoji_characters.sty', 'w')
# list of processed characters and exceptions:
charlist = ['2122']	# exception: ™
# create new LaTeX-unicode characters for (almost) every available twemoji:
f.write('% Code generated by "'+os.path.basename(sys.argv[0])+'".')
for filename in os.listdir('../emoji_images'):
	if not (filename.endswith('.pdf')):
		continue
	fullChar = filename.split('.pdf')[0]
	char = fullChar.split('-')[0]
	uniChar = unicode('\U'+char.zfill(8), 'unicode-escape').encode('utf8')
	# no duplicates, no ANSI-characters and no composite-characters:
	if (char not in charlist) and not(int(char,16) < 256) and char == fullChar:
		charlist.append(char)
		if int("1f1e6",16) <= int(char,16) <= int("1f1ff",16):
			f.write('\n\\newunicodechar{'+uniChar+'}{\coloremoji_flag:n{'+uniChar+'}} % '+fullChar)
		else:
			f.write('\n\\newunicodechar{'+uniChar+'}{{\coloremoji{'+uniChar+'}}} % '+fullChar)
	else:
		if not (char == fullChar):
			# special treatment for countrycodes (flags):
			if int("1f1e6",16) <= int(char,16) <= int("1f1ff",16):
				f.write('\n% Flag: '+fullChar)
			elif fullChar.split('-')[1] in {'1f3fb', '1f3fc', '1f3fd', '1f3fd', '1f3fe', '1f3ff'}:
				f.write('\n% Skin color variation: '+fullChar)
			else:
				f.write('\n% Composite character: '+fullChar)
		else:
			f.write('\n% ANSI character: '+fullChar)
print "Done."
f.close()