# -*- coding: UTF-8 -*-
import sys
import os
f = open('coloremoji_characters.sty', 'w')
# list of processed characters and exceptions:
charlist = ['2122']	# exception: ™
# list of countrycodes (flags)
countrylist = []
# create new LaTeX-unicode characters for (almost) every available twemoji:
f.write('% Code generated by "'+os.path.basename(sys.argv[0])+'".')
for filename in os.listdir('emoji_images'):
	char = filename.split('-')[0].split(".")[0]
	char_full = '\U'+char.zfill(8)
	uniChar = unicode(char_full, 'unicode-escape').encode('utf8')
	# no duplicates and no ANSI-Characters:
	if (char not in charlist) and not(int(char,16) < 256):
		# special treatment for countrycodes (flags):
		if int("1f1e6",16) <= int(char,16) <= int("1f1ff",16):
			if uniChar not in countrylist:
				countrylist.append(uniChar)
		else:
			charlist.append(char)
			f.write('\n\\newunicodechar{'+uniChar+'}{{\coloremoji{'+uniChar+'}}}')
f.write('\n\\ExplSyntaxOn')
for uniChar in countrylist:
	f.write('\n\\newunicodechar{'+uniChar+'}{\coloremoji_flag:n{'+uniChar+'}}')
f.write('\n\\ExplSyntaxOff')
f.close()